const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Behaviors.Pin,
		C3.Behaviors.Fade,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Tween,
		C3.Plugins.skymen_mask,
		C3.Plugins.TextBox,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Keyboard,
		C3.Plugins.Sparsha_FirebaseSDK,
		C3.Plugins.Sparsha_FirebaseRealtimeDatabase,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Sparsha_FirebaseSDK.Cnds.OnLoaded,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Text.Cnds.OnTypewriterTextFinished,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Behaviors.Fade.Cnds.OnFadeInEnd,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.PlatformInfo.Cnds.IsOnWindows,
		C3.Plugins.PlatformInfo.Cnds.IsOnMacOS,
		C3.Plugins.Mouse.Cnds.OnWheel,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.TextBox.Acts.SetCSSStyle,
		C3.Plugins.PlatformInfo.Cnds.IsOniOS,
		C3.Plugins.Sparsha_FirebaseRealtimeDatabase.Acts.AdvancedWriteLeaderboard,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.Browser.Acts.GoToURLWindow
	];
};
self.C3_JsPropNameTable = [
	{首頁BG: 0},
	{Button: 0},
	{連接成功: 0},
	{首頁btn: 0},
	{首頁BG2: 0},
	{Button2: 0},
	{首頁btn2: 0},
	{enter1: 0},
	{共用btn: 0},
	{BG: 0},
	{BG6: 0},
	{BG2: 0},
	{BG3: 0},
	{BG4: 0},
	{BG7: 0},
	{主要: 0},
	{關卡2劇情: 0},
	{主要2: 0},
	{主要3: 0},
	{主要4: 0},
	{主要5: 0},
	{主要6: 0},
	{固定: 0},
	{Text: 0},
	{youcannextscene: 0},
	{淡入淡出: 0},
	{共用btn2: 0},
	{stone: 0},
	{Subtract: 0},
	{請選出正確敘述多選: 0},
	{選擇一: 0},
	{選擇三: 0},
	{選擇二: 0},
	{更BG選項: 0},
	{拖放: 0},
	{補間動畫: 0},
	{moveplace2: 0},
	{Uplimit2: 0},
	{downlimit2: 0},
	{DragDrop: 0},
	{slipmove2: 0},
	{sliptop2: 0},
	{slipdown2: 0},
	{內容剪裁: 0},
	{背景剪裁: 0},
	{moveplace: 0},
	{Subtract2: 0},
	{Uplimit: 0},
	{downlimit: 0},
	{Text解答: 0},
	{共用itm: 0},
	{slipmove: 0},
	{sliptop: 0},
	{slipdown: 0},
	{select1: 0},
	{共用btn3: 0},
	{select2: 0},
	{共用btn7: 0},
	{select3: 0},
	{共用btn8: 0},
	{已送出: 0},
	{可使用按鈕: 0},
	{送出鈕: 0},
	{answer: 0},
	{看解析: 0},
	{繼續探險: 0},
	{BG5: 0},
	{解析層: 0},
	{答題完成: 0},
	{已參加: 0},
	{連接完成: 0},
	{btn7png: 0},
	{bnt72png: 0},
	{BG抽獎: 0},
	{BG收到: 0},
	{btn: 0},
	{女: 0},
	{男: 0},
	{資料完畢送出鈕: 0},
	{姓名: 0},
	{input_name: 0},
	{input_account: 0},
	{input_mail: 0},
	{input_unit: 0},
	{滑鼠: 0},
	{Touch: 0},
	{音頻: 0},
	{Browser: 0},
	{鍵盤: 0},
	{FirebaseV9SDK: 0},
	{FirebaseV9RDBasic: 0},
	{PlatformInfo: 0},
	{content: 0},
	{number: 0}
];

self.InstanceType = {
	首頁BG: class extends self.ISpriteInstance {},
	首頁btn: class extends self.ISpriteInstance {},
	首頁BG2: class extends self.ISpriteInstance {},
	首頁btn2: class extends self.ISpriteInstance {},
	共用btn: class extends self.ISpriteInstance {},
	BG: class extends self.ISpriteInstance {},
	BG6: class extends self.ISpriteInstance {},
	BG2: class extends self.ISpriteInstance {},
	BG3: class extends self.ISpriteInstance {},
	BG4: class extends self.ISpriteInstance {},
	BG7: class extends self.ISpriteInstance {},
	主要: class extends self.ISpriteInstance {},
	主要2: class extends self.ISpriteInstance {},
	主要3: class extends self.ISpriteInstance {},
	主要4: class extends self.ISpriteInstance {},
	主要5: class extends self.ISpriteInstance {},
	主要6: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	共用btn2: class extends self.ISpriteInstance {},
	stone: class extends self.ISpriteInstance {},
	Subtract: class extends self.ISpriteInstance {},
	請選出正確敘述多選: class extends self.ISpriteInstance {},
	選擇一: class extends self.ISpriteInstance {},
	選擇三: class extends self.ISpriteInstance {},
	選擇二: class extends self.ISpriteInstance {},
	更BG選項: class extends self.ISpriteInstance {},
	moveplace2: class extends self.ISpriteInstance {},
	Uplimit2: class extends self.ISpriteInstance {},
	downlimit2: class extends self.ISpriteInstance {},
	slipmove2: class extends self.ISpriteInstance {},
	sliptop2: class extends self.ISpriteInstance {},
	slipdown2: class extends self.ISpriteInstance {},
	內容剪裁: class extends self.IWorldInstance {},
	背景剪裁: class extends self.IWorldInstance {},
	moveplace: class extends self.ISpriteInstance {},
	Subtract2: class extends self.ISpriteInstance {},
	Uplimit: class extends self.ISpriteInstance {},
	downlimit: class extends self.ISpriteInstance {},
	Text解答: class extends self.ITextInstance {},
	共用itm: class extends self.ISpriteInstance {},
	slipmove: class extends self.ISpriteInstance {},
	sliptop: class extends self.ISpriteInstance {},
	slipdown: class extends self.ISpriteInstance {},
	共用btn3: class extends self.ISpriteInstance {},
	共用btn7: class extends self.ISpriteInstance {},
	共用btn8: class extends self.ISpriteInstance {},
	送出鈕: class extends self.ISpriteInstance {},
	answer: class extends self.ISpriteInstance {},
	看解析: class extends self.ISpriteInstance {},
	繼續探險: class extends self.ISpriteInstance {},
	BG5: class extends self.ISpriteInstance {},
	解析層: class extends self.ISpriteInstance {},
	答題完成: class extends self.ISpriteInstance {},
	btn7png: class extends self.ISpriteInstance {},
	bnt72png: class extends self.ISpriteInstance {},
	BG抽獎: class extends self.ISpriteInstance {},
	BG收到: class extends self.ISpriteInstance {},
	btn: class extends self.ISpriteInstance {},
	女: class extends self.ISpriteInstance {},
	男: class extends self.ISpriteInstance {},
	資料完畢送出鈕: class extends self.ISpriteInstance {},
	姓名: class extends self.ITextInstance {},
	input_name: class extends self.ITextInputInstance {},
	input_account: class extends self.ITextInputInstance {},
	input_mail: class extends self.ITextInputInstance {},
	input_unit: class extends self.ITextInputInstance {},
	滑鼠: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	音頻: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	鍵盤: class extends self.IInstance {},
	FirebaseV9SDK: class extends self.IInstance {},
	FirebaseV9RDBasic: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {}
}